name: Main

on:
  push:
    branches: [main]

jobs:
  build-lint-test:
    name: Validate
    uses: ./.github/workflows/build-lint-test.yml
    secrets:
      RPC_URL_LIST_MAINNET: ${{ secrets.RPC_URL_LIST_MAINNET }}
      RPC_URL_LIST_NILE_TESTNET: ${{ secrets.RPC_URL_LIST_NILE_TESTNET }}
      RPC_URL_LIST_SHASTA_TESTNET: ${{ secrets.RPC_URL_LIST_SHASTA_TESTNET }}
      RPC_URL_LIST_LOCALNET: ${{ secrets.RPC_URL_LIST_LOCALNET }}
      EXPLORER_MAINNET_BASE_URL: ${{ secrets.EXPLORER_MAINNET_BASE_URL }}
      EXPLORER_NILE_BASE_URL: ${{ secrets.EXPLORER_NILE_BASE_URL }}
      EXPLORER_SHASTA_BASE_URL: ${{ secrets.EXPLORER_SHASTA_BASE_URL }}
      PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
      LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
      TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
      STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
      SECURITY_ALERTS_API_BASE_URL: ${{ secrets.SECURITY_ALERTS_API_BASE_URL }}
      NFT_API_BASE_URL: ${{ secrets.NFT_API_BASE_URL }}

  sonarcloud:
    permissions:
      id-token: write
      contents: write
      checks: write
      pull-requests: write
      actions: read
    name: SonarCloud
    needs: build-lint-test
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
    outputs:
      PASSED: ${{ steps.set-output.outputs.PASSED }}
    steps:
      - name: Set PASSED output
        id: set-output
        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-completed
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-completed.outputs.PASSED }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi

  is-release:
    # Filtering by `push` events ensures that we only release from the `main` branch, which is a
    # requirement for our npm publishing environment.
    # The commit author should always be 'github-actions' for releases created by the
    # 'create-release-pr' workflow, so we filter by that as well to prevent accidentally
    # triggering a release.
    if: github.event_name == 'push' && startsWith(github.event.head_commit.author.name, 'github-actions')
    needs: all-jobs-pass
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/action-is-release@v1
        id: is-release

  publish-release:
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    name: Publish release
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RPC_URL_LIST_MAINNET: ${{ secrets.RPC_URL_LIST_MAINNET }}
      RPC_URL_LIST_NILE_TESTNET: ${{ secrets.RPC_URL_LIST_NILE_TESTNET }}
      RPC_URL_LIST_SHASTA_TESTNET: ${{ secrets.RPC_URL_LIST_SHASTA_TESTNET }}
      RPC_URL_LIST_LOCALNET: ${{ secrets.RPC_URL_LIST_LOCALNET }}
      EXPLORER_MAINNET_BASE_URL: ${{ secrets.EXPLORER_MAINNET_BASE_URL }}
      EXPLORER_NILE_BASE_URL: ${{ secrets.EXPLORER_NILE_BASE_URL }}
      EXPLORER_SHASTA_BASE_URL: ${{ secrets.EXPLORER_SHASTA_BASE_URL }}
      PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
      LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
      TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
      STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
      SECURITY_ALERTS_API_BASE_URL: ${{ secrets.SECURITY_ALERTS_API_BASE_URL }}
      NFT_API_BASE_URL: ${{ secrets.NFT_API_BASE_URL }}
