name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      RPC_URL_LIST_MAINNET:
        required: true
      RPC_URL_LIST_NILE_TESTNET:
        required: true
      RPC_URL_LIST_SHASTA_TESTNET:
        required: true
      PRICE_API_BASE_URL:
        required: true
      LOCAL_API_BASE_URL:
        required: true
      TOKEN_API_BASE_URL:
        required: true
      STATIC_API_BASE_URL:
        required: true
      SECURITY_ALERTS_API_BASE_URL:
        required: true
      NFT_API_BASE_URL:
        required: true
      EXPLORER_MAINNET_BASE_URL:
        required: true
      EXPLORER_NILE_BASE_URL:
        required: true
      EXPLORER_SHASTA_BASE_URL:
        required: true
      TRONGRID_API_KEY:
        required: true
      TRONGRID_BASE_URL_MAINNET:
        required: true
      TRONGRID_BASE_URL_NILE:
        required: true
      TRONGRID_BASE_URL_SHASTA:
        required: true
      TRON_HTTP_BASE_URL_MAINNET:
        required: true
      TRON_HTTP_BASE_URL_NILE:
        required: true
      TRON_HTTP_BASE_URL_SHASTA:
        required: true
jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - uses: MetaMask/action-publish-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          yarn install
          yarn workspace @metamask/tron-wallet-snap build
        env:
          ENVIRONMENT: production
          RPC_URL_LIST_MAINNET: ${{ secrets.RPC_URL_LIST_MAINNET }}
          RPC_URL_LIST_NILE_TESTNET: ${{ secrets.RPC_URL_LIST_NILE_TESTNET }}
          RPC_URL_LIST_SHASTA_TESTNET: ${{ secrets.RPC_URL_LIST_SHASTA_TESTNET }}
          EXPLORER_MAINNET_BASE_URL: ${{ secrets.EXPLORER_MAINNET_BASE_URL }}
          EXPLORER_NILE_BASE_URL: ${{ secrets.EXPLORER_NILE_BASE_URL }}
          EXPLORER_SHASTA_BASE_URL: ${{ secrets.EXPLORER_SHASTA_BASE_URL }}
          PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
          LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
          TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
          STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
          SECURITY_ALERTS_API_BASE_URL: ${{ secrets.SECURITY_ALERTS_API_BASE_URL }}
          NFT_API_BASE_URL: ${{ secrets.NFT_API_BASE_URL }}
          TRONGRID_API_KEY: ${{ secrets.TRONGRID_API_KEY }}
          TRONGRID_BASE_URL_MAINNET: ${{ secrets.TRONGRID_BASE_URL_MAINNET }}
          TRONGRID_BASE_URL_NILE: ${{ secrets.TRONGRID_BASE_URL_NILE }}
          TRONGRID_BASE_URL_SHASTA: ${{ secrets.TRONGRID_BASE_URL_SHASTA }}
          TRON_HTTP_BASE_URL_MAINNET: ${{ secrets.TRON_HTTP_BASE_URL_MAINNET }}
          TRON_HTTP_BASE_URL_NILE: ${{ secrets.TRON_HTTP_BASE_URL_NILE }}
          TRON_HTTP_BASE_URL_SHASTA: ${{ secrets.TRON_HTTP_BASE_URL_SHASTA }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
          include-hidden-files: true
          retention-days: 4
          path: |
            ./packages/**/dist
            ./packages/snap/snap.manifest.json
            ./node_modules/.yarn-state.yml

  publish-npm-dry-run:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Dry Run Publish
        uses: MetaMask/action-npm-publish@v5
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          subteam: S042S7RE4AE # @metamask-npm-publishers
        env:
          SKIP_PREPACK: true

  publish-npm:
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Publish
        uses: MetaMask/action-npm-publish@v5
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
        env:
          SKIP_PREPACK: true
